<?php

$photoTable = new Logged_Model_DbTable_Photo();
$photos = $photoTable->getPhotos($this->id, "user");

if ($GLOBALS["session"]->id == $this->id) {
    $owner = 1;
}

$photo = new Logged_Model_Photo();

$currentPhotoid = $photoTable->getCurrent($this->id);
?>
<script type="text/javascript" src="/scripts/libraries/ajaxupload.js"></script>
<script>

    $(document).ready(function(){


        ajaxUpload = new AjaxUpload("#imageFile",{

            action: '/logged/ajax/uploadphoto/',
            name: 'imageFile',
            data: {
                MAX_FILE_SIZE : '1000000'
            },
            onSubmit : function(){

                $(".statusDisplay").html('<img class="spinner" src="/graphics/en/UI/spinning_indicator.gif" />');
                this.setData({
                    'location': $("#location").val(),
                    'caption':$("#caption").val(),
                    'MAX_FILE_SIZE' : '2000000'
                });
                //   this.disable();
            },

            onChange: function(file,extention){

                $(".statusDisplay").html("File selected: "+file);

            },

            autoSubmit: false,

            onComplete: function(file,responce){


                $(".statusDisplay").html(responce);

                if (responce == "Upload complete!"){
                    window.setTimeout('location.reload()', 1500);
                }

            }


        });
        
    });

</script>
<h2 class="userName">
    <a href="/<?=$this->username;?>/profile"><img class="userProfilePicThmbnl" src="<?=$photo->display($this->id,"user","small");?>" /></a>
    <?php
    if ($owner

    )echo"My";else
            echo"$this->fullname's"; ?> Profile Pictures
    <div class="picCounter">
        <div><strong><span class="picCounter"><?php
                    if (count($photos) == 1)
                        echo count($photos) . "</span></strong> Photo</div>"; else
                        echo count($photos) . "</span></strong> Photos</div>";

                    $offset = 15 * ($this->page - 1);
                    $viewablePages = ceil(count($photos) / 15);

                    if ($offset < 0) {
                        $offset = 0;
                    }
                    if ($this->page < 1) {
                        $this->page = 1;
                    }

                    $photos = $photoTable->getPhotos($this->id, "user", FALSE, 15, $offset);
                    ?>
                    </strong>
                </span>
                    </div>
                    </h2>

                    
                    <?php 
                    if($owner){
                    echo <<<MARKUP
                    <div class="privacySettingsBtn" style="visibility: hidden"><a href="console/privacy">Privacy Settings</a></div>
                    <a class="UIButton grey large changeProfilePic" onclick="$('#profilePicUpload').fadeIn();"><span class="UIButtonTxt">Change my profile picture</span></a>
MARKUP;
                    }
                    ?>

                    <ul <?=($viewablePages <= 1)?"style='display:none;'":NULL;?> class="pagination" id="photosPaginationTop">
                        <li class="previous <?=($this->page == 1) ? "off" : NULL; ?>">
                            <?php
                            if ($this->page == 1) {

                                echo "&laquo;&nbsp;Previous";
                            } else {
                                $prePage = $this->page - 1;
                                echo "<a href=\"?page=$prePage\">&laquo;&nbsp;Previous</a>";
                            }
                            ?></li>

                        <?php
                        $i = 1;

                        while ($i <= $viewablePages) {

                            if ($i == $this->page) {
                                $paginArray[$i] = "<li class=\"active\">$i</li>";
                            } else {
                                $paginArray[$i] = "<li><a href=\"?page=$i\">$i</a></li>";
                            }

                            $i++;
                        }

                        foreach ($paginArray as $pagin) {
                            echo $pagin;
                        }
                        ?>

                        <li class="next <?=($this->page == $viewablePages) ? "off" : NULL; ?>"><?php
                            if ($this->page == $viewablePages) {

                                echo "&nbsp;Next&raquo;";
                            } else {
                                $prePage = $this->page + 1;
                                echo "<a href=\"?page=$prePage\">&nbsp;Next&raquo;</a>";
                            }
                            ?></li>
                    </ul>
                    <div class="mainContainer">
          <? if($owner): ?>
   <div class="popup profilePicUpload <?php if($_GET["upload"] != true): ?>hidden<?php endif; ?>" id="profilePicUpload">
        <h3>Change your profile picture</h3><span class="cancelBtn" onclick="$('#profilePicUpload').fadeOut();">Cancel</span>
        <hr class="UIHSeparator" />
        <form enctype="multipart/form-data">
         <span class="description">Max. file size: 2 MB. Accepted file formats: PNG, JPG, GIF.</span>
         <div class="statusDisplay">Upload an image!</div>
         <a id="imageFile" class="UIButton grey large UIFileUploadControl"><span class="UIButtonTxt">Choose file</span></a>
         <div class="details">
          <h3>Care to fill out some details?</h3>
          <dt>Location:</dt><dd><input id="location" type="text" class="UITextInput" /></dd>
          <dt>Caption:</dt><dd><textarea id="caption"></textarea></dd>
         </div>
         <div class="UIPanel">
          <a class="UIButton green large save" onclick="ajaxUpload.submit();"><span class="UIButtonTxt">Save</span></a>
         </div>
        </form>
       </div>
    <?php endif; ?>
                        <div class="thmbnls">
                            
                            <?php if(!$photos): ?>
                            <h3 class=\"noPhotos\" style="margin-left:250px;">No photos to display</h3>
                            <?php endif; ?>
                            
                            <table cellspacing="0" cellpadding="0">
                                <tbody>

                                    <?php $i = 0;
                                    $photos = array_reverse($photos);
                                    if ($photos) {
                                        foreach ($photos as $thumb) {

                                            $i++;

                                            $photoid = $thumb['id'];
                                            $caption = htmlspecialchars($thumb['caption'],ENT_QUOTES ,"UTF-8");

                                            if($i == 1) {
                                                echo "<tr>";
                                            }
                                            echo <<<MARKUP
            <td class="thmbnl" id="P$photoid">
            <a class="thmbnlImg" href="/$this->username/gallery/photo/$photoid">
            <img class="thmbnlImg" title="$caption" src="{$photo->display($photoid,"photo","med")}" />
            </a>                                
            </td>
MARKUP;

                                            if($i == $c+4) {
                                                $c = $i;
                                                echo "</tr><tr>";
                                            }

                                        }
                                    } else {
                                        //echo "<h3 class=\"noPhotos\">No photos to display</h3>";
}
?>

                                </tbody>
                            </table>
                        </div>
                    </div>
