<?php
$photo = new Logged_Model_Photo();

$caption = $this->photo[0]['caption'];
$location = $this->photo[0]['location'];
$time = rawurlencode(Model_StaticFunctions::formatDateFromTimestamp($this->photo[0]['time'], "uploaded"));
$photoid = $this->photoid;
$userid = $this->photo[0]['userid'];

$photoTable = new Logged_Model_DbTable_Photo();
$currentPhotoid = $photoTable->getCurrent($userid);

$severName = $_SERVER['SERVER_NAME'];

$photoLink = $photo->display($photoid, "photo", "full");

$session = Model_StaticFunctions::sessionContent();

$username = $session->username;

if($session->id == $userid) {
    $owner = 1;
}


if($currentPhotoid == $photoid) {
    $current = 1;
}


?>
<photoDetails>
    <photoLink>
        <?=rawurlencode($photoLink);?>
    </photoLink>

    <caption>
        <?php if($caption){
            echo rawurlencode("<div id=\"caption\">$caption</div>
            <div id=\"addCaption\" style=\"display:none;\">
            <a class=\"addCaption\" onclick=\"toggleEditor('show');\">Add a caption</a>
            </div>"); }
            else{echo rawurlencode("<div id=\"caption\">$caption</div>
            <div id=\"addCaption\">
            <a class=\"addCaption\" onclick=\"toggleEditor('show');\">Add a caption</a>
            </div>");
            }
            ?>
    </caption>

    <location>
        <?php if($location) {
            echo rawurlencode("<dt class=\"location\">Location:</dt><dd id='location'>$location</dd>");
        } else {
            echo rawurlencode("<dt class=\"location\" style=\"display:none;\">Location:</dt><dd id='location'>$location</dd>");
        }
        ?>
    </location>

    <time>
        <?=$time;?>
    </time>

    <photoActions>
        <?php
        $markup = <<<MARKUP
        <div class="popup share" id="sharePopup" style="display:none;top:40%;">
            <h3>Share this photo with others</h3><span class="cancelBtn" onclick="$('#sharePopup').fadeOut();">Cancel</span>
            <p>Give them this link:</p>
            <input type="text" readonly="true" class="UITextInput" id="shareInput" onClick="$(this).select();" value="http://$severName/$username/gallery/photo/$photoid" />
        </div>
        <h3>Actions</h3>
MARKUP;

        if($owner) {
            $markup = $markup . <<<MARKUP
  <div id="editDetails" onclick="toggleEditor('show');"><a>Edit details&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a></div>
   <div onclick="$('#confirmDel').show();" id="deletePhoto"><a>Delete this photo</a></div>
MARKUP;
        }else {
            $markup = $markup . "";
        }
        if($owner && !$current) {
            $markup = $markup . <<<MARKUP
     <div id="makeProfilePic" onclick="ajaxMakeCurrent($photoid);$('#infoPictureChange').fadeIn();"><a>Use as profile picture</a></div>
MARKUP;
        }


        $markup = $markup . <<<MARKUP
        <div id="sharePhoto" onclick="$('#sharePopup').fadeIn();$('#shareInput').select();" ><a>Share&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a></div>
        <div id="reportPhoto" class="hidden"><a>Report this photo</a></div>
MARKUP;
        echo rawurlencode($markup);
        ?>
    </photoActions>

    <confirmDel>
        <?php if($owner) {
            $confirmDel = <<<MARKUP

<div style="display: none; position:fixed; bottom: 50%;"  class="UIWindow confirm" id="confirmDel">
            <div class="titleBar">
                <h2>Confirm Action</h2><span class="closeBtn" title="Close" onclick="$('#confirmDel').fadeOut();$('#pageOverlay').hide();" ><a><span class="UIIcon px16 cross"></span></a></span>
            </div>
            <div class="UIWindowContents">
                <p class="message">Are you sure you want to delete this photo?</p>
                <hr />
                <div id="yesBtn">
                <a onclick="ajaxDelete('$photoid','photo');$('#confirmDel').fadeOut();$('#pageOverlay').hide();window.setTimeout('window.location = \'/$username/gallery\'', 1000);" class="UIButton confirmBtn green"><span>Yes</span></a>
                </div>
                <a onclick="$('#confirmDel').fadeOut();$('#pageOverlay').hide();" class="UIButton cancelBtn green"><span>Cancel</span></a>
            </div>
        </div>

MARKUP;
        }else {
            $confirmDel = "";
        }

        echo rawurlencode($confirmDel);
        ?>
    </confirmDel>

    <photoid><?=$photoid;?></photoid>

    <likesDislikes>
        <?php
        $likesAndDislikes = new Logged_Model_LikeAndDislike();
        $likesAndDislikes = $likesAndDislikes->displayLikeAndDislike($photoid, "photo");
        echo rawurlencode($likesAndDislikes['display']);
        ?>
    </likesDislikes>

    <showComments>
        <?php

        $comments = new Logged_Model_DbTable_Comment();
        $numOfComments = count($comments->getAllCommentsOnElm($photoid, "photo"));

        switch(true) {
            case ($numOfComments == 0):

                $showCommentsMarkup =  <<<MARKUP
             <a class="showAllCommentsBtnLink" style="display:none;" onclick="ajaxDisplayComments($photoid,'photo');$('#commentWindow').fadeIn();" ></a>
MARKUP;
                break;

            case ($numOfComments == 1):

                $showCommentsMarkup = <<<MARKUP
                  <a class="showAllCommentsBtnLink" onclick="ajaxDisplayComments($photoid,'photo');$('#commentWindow').fadeIn();" ><span class="UIIcon px16 comment"></span>Show <span class="commentCount">$numOfComments</span> comment.</a>
MARKUP;
                break;

            case ($numOfComments > 1):

                $showCommentsMarkup = <<<MARKUP

                  <a class="showAllCommentsBtnLink" onclick="ajaxDisplayComments($photoid,'photo');$('#commentWindow').fadeIn();" ><span class="UIIcon px16 comment"></span>Show all <span class="commentCount">$numOfComments</span> comments.</a>
MARKUP;

                break;

        }

        echo rawurlencode($showCommentsMarkup);

        ?>
    </showComments>
    <userActions>
        <?php
        
        $likeAndDislike = new Logged_Model_LikeAndDislike();
        $likeAndDislike = $likeAndDislike->displayLikeAndDislike($photoid,'photo');

        $likeBtn = "<a>Like</a>";
        $dislikeBtn = "<a>Dislike</a>";

        if ($likeAndDislike['Lyou'] || $likeAndDislike['LyouAndOther']|| $likeAndDislike['LyouAndNumOther']) {
            $likeBtn = "<a>Remove like</a>";
        }
        if ($likeAndDislike['Dyou'] || $likeAndDislike['DyouAndOther']|| $likeAndDislike['DyouAndNumOther']) {
            $dislikeBtn = "<a>Remove dislike</a>";
        }

        $markup = <<<MARKUP
            <span class="commentBtn">Comment</span> &middot;
                <span class="likeBtn" onclick="ajaxLike($photoid,'photo');" >$likeBtn</span> &middot;
                <span class="dislikeBtn" onclick="ajaxDislike($photoid,'photo');">$dislikeBtn</span>
MARKUP;
    echo rawurlencode($markup);
        ?>
    </userActions>

    <saveChangesBtn>
        <?= rawurlencode("<a class=\"UIButton green save\" onclick=\"ajaxEditPhotoDetails($photoid,$('#editCaption').val(),$('#editLocation').val());\"><span>Save Changes</span></a>");?>
    </saveChangesBtn>

    <commentBtn>
        <?= rawurlencode("<a class=\"UIButton green post\"><span>Comment</span></a>"); ?>
    </commentBtn>

    <commentBtnWindow>
        <?= rawurlencode("<a onclick=\"ajaxCreateComment($('#minieditorWindow').html(),$photoid,'photo','commentWindow');\" class=\"UIButton green post\"><span>Comment</span></a>"); ?>
    </commentBtnWindow>

</photoDetails>