<style>
    html.help.console #stats {
background: transparent url(/graphics/en/icons/statistics_32px.png) no-repeat 0px 0px;
}
</style>
<div class="mainWrapper">
    <h3>Settings</h3>
    <p>The Settings is the center for controlling all of your settings. From here you can change your password, your name. Below, we explain the various settings found in each section of the Settings.</p>
    <dt id="about">The "About" Section</dt>
    <dd>This section is pretty basic for now. It just shows you what version of Scapehouse you're currently using. This may seem useless right now, but it will become much more important later on as we release newer versions of Scapehouse.</dd>
    <dt id="account" >The "Account" Section</dt>
    <dd >This section handles all of your account management. You can do the following:
        <ul>
            <li>Change your name.</li>
            <li>Change your password.</li>     
          <!--  <li>Deactivate your account.</li> -->
        </ul>
    </dd>
    <dt id="stats" >The "Stats" Section</dt>
    <dd>This section gives you an outline of your footprint on Scapehouse.</dd>
    <!--<dt id="notifs">The "Notifications" Section</dt>
    <dd >When users perform certain actions on Scapehouse (<span class="example">example: someone comments on one of your replies</span>), you will receive notifications to keep you informed. This section allows you to choose when to receive notifications. If you want, you can turn off all notifications.</dd>
    <dt id="privacy">The "Privacy" Section</dt>
    <dd>You might want to spend some time in this section. We give you total control over all the details. You choose who gets to see each and every one of them. To learn more, check out <a href="/help/privacy">"Privacy @ Scapehouse"</a>.</dd>
     -->
</div>
