<div class="mainWrapper">
    <h3>Scapehouse Emoticon Guide</h3>
    <table>
        <tr class="tableHeader">
            <th></th>
            <th>Emoticon Name</th>
            <th>Emoticon Value</th>
        </tr>
        <tr>
            <td><span class="emoticon wink"></span></td>
            <td>Wink</td>
            <td>;)</td>
        </tr>
        <tr>
            <td><span class="emoticon winkLaugh"></span></td>
            <td>Laughing wink</td>
            <td>;D</td>
        </tr>
        <tr>
            <td><span class="emoticon winkTongue"></span></td>
            <td>Wink with tongue out</td>
            <td>;P</td>
        </tr>
        <tr>
            <td><span class="emoticon cry"></span></td>
            <td>Crying</td>
            <td>:'(</td>
        </tr>
        <tr>
            <td><span class="emoticon sad"></span></td>
            <td>Sad</td>
            <td>:(</td>
        </tr>
        <tr>
            <td><span class="emoticon angel"></span></td>
            <td>Angel</td>
            <td>(a)</td>
        </tr>
        <tr>
            <td><span class="emoticon blush"></span></td>
            <td>Embarassed</td>
            <td>:$</td>
        </tr>
        <tr>
            <td><span class="emoticon cool"></span></td>
            <td>Cool</td>
            <td>(cool)</td>
        </tr>
        <tr>
            <td><span class="emoticon heart"></span></td>
            <td>Heart</td>
            <td>&lt;3</td>
        </tr>
        <tr>
            <td><span class="emoticon brokenHeart"></span></td>
            <td>Broken heart</td>
            <td>&lt;/3</td>
        </tr>
        <tr>
            <td><span class="emoticon nerdy"></span></td>
            <td>Nerdy</td>
            <td>8|</td>
        </tr>
        <tr>
            <td><span class="emoticon sleepy"></span></td>
            <td>Sleepy</td>
            <td>(zzz)</td>
        </tr>
        <tr>
            <td><span class="emoticon surprised"></span></td>
            <td>Surprised</td>
            <td>:O</td>
        </tr>
        <tr>
            <td><span class="emoticon smile"></span></td>
            <td>Smiling</td>
            <td>:)</td>
        </tr>
        <tr>
            <td><span class="emoticon angry"></span></td>
            <td>Angry</td>
            <td>:@</td>
        </tr>
        <tr>
            <td><span class="emoticon speechless"></span></td>
            <td>Speechless</td>
            <td>:|</td>
        </tr>
        <tr>
            <td><span class="emoticon laugh"></span></td>
            <td>Laughing</td>
            <td>:D</td>
        </tr>
        <tr>
            <td><span class="emoticon sh"></span></td>
            <td>Scapehouse</td>
            <td>(sh)</td>
        </tr>
        <tr>
            <td><span class="emoticon facebook"></span></td>
            <td>Facebook</td>
            <td>(fb)</td>
        </tr>
        <tr>
            <td><span class="emoticon msn"></span></td>
            <td>MSN</td>
            <td>(msn)</td>
        </tr>
        <tr>
            <td><span class="emoticon tongue"></span></td>
            <td>Tongue out</td>
            <td>:P</td>
        </tr>
        <tr>
            <td><span class="emoticon worried"></span></td>
            <td>Confused</td>
            <td>:S</td>
        </tr>
        <tr>
            <td><span class="emoticon headBang"></span></td>
            <td>Banging head</td>
            <td>(banghead)</td>
        </tr>
        <tr>
            <td><span class="emoticon skype"></span></td>
            <td>Skype</td>
            <td>(skype)</td>
        </tr>
        <tr>
            <td><span class="emoticon twitter"></span></td>
            <td>Twitter</td>
            <td>(twitter)</td>
        </tr>
        <tr>
            <td><span class="emoticon hardLaugh"></span></td>
            <td>Hard laugh</td>
            <td>(xD)</td>
        </tr>
        <tr>
            <td><span class="emoticon hardLaughTongue"></span></td>
            <td>Hard laugh with tongue out</td>
            <td>(xP)</td>
        </tr>
        <tr>
            <td><span class="emoticon youtube"></span></td>
            <td>YouTube</td>
            <td>(youtube)</td>
        </tr>
        <tr>
            <td><span class="emoticon blackberry"></span></td>
            <td>BlackBerry</td>
            <td>(bb)</td>
        </tr>
        <tr>
            <td><span class="emoticon mp3"></span></td>
            <td>MP3 player</td>
            <td>(mp3)</td>
        </tr>
    </table>
</div>