<div class="mainWrapper">
    <h3>Known issues</h3>
    <p>The Publishers on Scapehouse do not seem to function properly when using the latest version of Opera (10.60). There is no definite time as to when this issue will be fixed.<br /><br />
    <strong>Solution:</strong> for the time being, the only solution to this issue is to browse the site using:
    <ul>
    <li>Google Chrome 4 or higher</li>
    <li>Safari 4 or higher</li>
    <li>Firefox 3.5 or higher</li>
    <li>Internet Explorer 8 or Higher</li>
    </ul></p>
</div>