<div class="mainWrapper">
            <h3>Noteboard</h3>
            <p>Noteboard allows you to easily contact specific people directly by leaving them notes.</p>
            <p>Notes are short messages, and can be no more than 160 characters. You can customize the color of your note before you pin it.</p>
            <img src="/graphics/en/imgs/help/noteboard.png" alt="The Noteboard." width="493" style="display:block;margin:0 auto;" />
            <p>Once you pin a note on someone's board, that person will be notified that you left them a note.</p>
    </div>