<div class="mainWrapper">
    <h3>Profiles</h3>
    <h4>Timeline</h4>
    <p>The timeline shows your most recently posted scapes.</p>
    <h4>Info</h4>
    <p>You and other people who come to your profile can view your information using the Info tab and you have complete control over what information others can see.</p>
    <h5>How to get started:</h5>
    <ol>
        <li>Go to your profile, go into editing mode by clicking the "Edit my profile" link under the "Summary" section and start filling in your details.</li><br />
        <li>We help you keep your profile organized, use the "Add another" buttons next to the input fields to add more details to your profile.</li><br />
        <li>When you are done hit "Save Changes" at the bottom, and you're done! your profile has been updated, you can now go the the Info tab and see how your profile looks.</li>
    </ol>
</div>