<?php $session = Model_StaticFunctions::sessionContent();?>
<h2 id="pageTitle">Settings<span class="UIBreadCrumb"><a href="/<?=$session->username?>/console">Settings Main Page</a>&nbsp;&raquo;&nbsp;<span class="currentLocation">About</span></span></h2>

<div class="info">
        <div class="leaderboard" >
                <h2 class="theBigO"></h2>
                <p>You're using Scapehouse <span class="version">1.0 <span class="releaseStage"></span></span></p>
        </div>
        <div class="newStuff">
                <h3>Features in 1.0<span class="launchDate">Launched on: Friday, September 24<sup>th</sup>, 2010</span></h3>
                <ul>
                        <li class="new"><span class="listItemTxt">See who's online<sup class="newMarker">New!</sup></span></li>
                        <li class="new"><span class="listItemTxt">Real-time notifications<sup class="newMarker">New!</sup></span></li>
                        <li class="new"><span class="listItemTxt">Themes<sup class="newMarker">New!</sup></span></li>
                        <li class="new"><span class="listItemTxt">Noteboard<sup class="newMarker">New!</sup></span></li>
                        <li><span class="listItemTxt">Publish scapes</span></li>
                        <ul>
                                <li><span class="listItemTxt">Post replies and comments</span></li>
                        </ul>
                        <li><span class="listItemTxt">Upload profile pictures</span></li>
                        <li><span class="listItemTxt">Notifications</span></li>
                        <li><span class="listItemTxt">Scapehouse Profiles</span></li>
                </ul>
        </div>
</div>